//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumWEB.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historical_Task
    {
        public long ID { get; set; }
        public Nullable<long> ID_Task { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<long> ID_UserLog { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual Users Users { get; set; }
    }
}
