//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumWEB.API
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScrumDataEntities : DbContext
    {
        public ScrumDataEntities()
            : base("name=ScrumDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Backlog> Backlog { get; set; }
        public virtual DbSet<Historical_Task> Historical_Task { get; set; }
        public virtual DbSet<Paper> Paper { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<Sprint> Sprint { get; set; }
        public virtual DbSet<Task> Task { get; set; }
        public virtual DbSet<User_Project> User_Project { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
